tasks:
  - init: echo "Starting Init"
    # command: echo "Replace me with something that should run on every start, or just
    #   remove me entirely."
image:
  file: .gitpod.Dockerfile

ports:
  - port: 41555
    onOpen: notify

  - port: 37737
    onOpen: notify

  - port: 36347
    onOpen: notify
